### ISSUE TITLE
Afford one-tap "been" on detail screen when at place

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner-android#102]
When the user is at a location, the detail screen's "user flag" component should have a special format:
https://marvelapp.com/4c295bb/screen/44571061

![image](https://user-images.githubusercontent.com/128699/41663611-d4eb4dcc-7471-11e8-8229-28738830c299.png)

Tapping "I'm here now" marks the place as been. The UI should then appear just as it normally would when the user has been to that place.

Tapping the X restores the component to its default format ("Been here? Want to go?", etc).

See #46

**Comment by flibbertigibbet** [comment]
Obviated by #157
