### ISSUE TITLE
Search function not working on LG G4

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner-android#146]
Per Olivia at CAC: "The search bar is there, and I am able to type into it. Nothing happens when I tell it to search, though. The auto-complete function has not revealed itself to me."

**Comment by jcahail** [comment]
![screenshot_2018-07-23-12-56-47](https://user-images.githubusercontent.com/24727081/43093698-c3e06afe-8e7e-11e8-95a4-cc29460eab50.png)
![screenshot_2018-07-23-12-56-53](https://user-images.githubusercontent.com/24727081/43093699-c3ea9b00-8e7e-11e8-9196-652cf84b57ab.png)
![screenshot_2018-07-23-12-57-01](https://user-images.githubusercontent.com/24727081/43093700-c3f58f9c-8e7e-11e8-80cf-04e80a2420fb.png)
![screenshot_2018-07-23-12-54-32](https://user-images.githubusercontent.com/24727081/43093701-c401e8a0-8e7e-11e8-96f2-529de4946167.png)
![screenshot_2018-07-23-12-56-41](https://user-images.githubusercontent.com/24727081/43093702-c40c3d78-8e7e-11e8-95ec-967ff0fed384.png)

**Comment by flibbertigibbet** [comment]
Reproducible with an emulator on 6.0 (Marshmallow, API level 23).
