### ISSUE TITLE
Categories grid to filtered place list

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner-android#15]
Implement clicking on a category card on the home view by going to place list, filtered to the selected category.

Depends on #18 for filtering implementation.

**Comment by flibbertigibbet** [comment]
@lederer what would you like us to do for the category card images on the home view? They're fixed placeholders now; I'm guessing we'll either want to swap them out with new images, or pull dynamically somehow from things of that category. If there's some related code changes you'd like us to make to support something like that, please let us know, and we can maybe do that with this task.

**Comment by lederer** [comment]
I think these should be pulled dynamically from the items in their corresponding category.

Ideally, each category image would be unique (when possible). If that's too complex to implement within our constraints, we could just pick a random item from each category. That oughta do a decent enough job of minimizing duplicates.

**Comment by flibbertigibbet** [comment]
What should we do for a fallback if there is nothing in that category?

**Comment by lederer** [comment]
We should probably just hide any empty categories from the home screen.
