### ISSUE TITLE
Place and event list filtering

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner-android#18]
Implement filtering for the the places and events list views: [wireframe](https://marvelapp.com/4c295bb/screen/37237004).

Depends on #8.

**Comment by maurizi** [comment]
From @lederer:

> I should add some additional clarification to filter behavior…
> 
> _Within_ a given filter, eg Category, multiple values are allowed and they should be OR'd. But _across_ filters should be AND'd.
> 
> Correct examples:
> - (Nature OR Exercise)
> - (Liked OR Want to go)
> - (Nature) AND (Want to go)
> - (Nature OR Exercise) AND (Liked OR Want to go)
