### ISSUE TITLE
Search bar in toolbar button

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner-android#19]
Implement searching destinations and events: [wireframe](https://marvelapp.com/4c295bb/screen/37237007). Open search from toolbar search buttons.

**Comment by lederer** [comment]
Hmm. Search widget seems fine – except for the home screen transparent app bar situation. Are we able to hook into the search widget lifecycle to, say, change the bg color of the app bar while in search mode?

**Comment by flibbertigibbet** [comment]
I've found a way to reliably hook into the event for entering search mode, but haven't yet found a good way to know when the search gets closed/completed/cancelled, which would allow for removing custom styling.

I'll look around more and see what I can come up with.

**Comment by flibbertigibbet** [comment]
It looks like we should be able to control the background for the search query window with [custom styling for the widget](https://philio.me/styling-the-searchview-with-appcompat-v21/). I'll give that a try.
