### ISSUE TITLE
Create timeline for required Android updates

### ISSUE THREAD

**Issue by ddohler** [azavea/cac-tripplanner-android#195]
Google will now de-list apps from the Play store if they fall too far out of date: https://android-developers.googleblog.com/2022/04/expanding-plays-target-level-api-requirements-to-strengthen-user-security.html

We should figure out when we'll need to update the Android app in order to keep it from being de-listed.

**Comment by ktohalloran** [comment]
Google sets these deadlines using distinctions between "existing apps" and "app updates". Based on the rules associated with each type and the interpretation that our app is an "existing app", we have until **November 1, 2022** to upgrade to support a `targetSdkVersion` (also called target API level in the Google Play docs) of at least 30 (we are currently at 29), and until **November 1, 2023** to update to version 31. Should we need more time to comply, we can complete a 6-month extension request form (though this doesn't seem to be available yet).

As a note, based on this distinction between "existing apps" and "app updates", it seems that we can't make any other updates to our app that do not include the `targetSdkVersion` upgrade before November 1, 2022, or again after that point if they do not include the upgrade to support version 31. Ultimately, this policy change is establishing a pattern where, moving forward, we can only remain at most 2 years out of date if we have no intention of updating, and 1 year out of date if we do.

Exact timelines and the definitions of "existing app" vs "app update" can be found [here](https://support.google.com/googleplay/android-developer/answer/11926878).

**Comment by ddohler** [comment]
Thanks, this is super helpful!
