### ISSUE TITLE
Publish upgraded application to Play Store by November 1, 2022

### ISSUE THREAD

**Issue by ddohler** [azavea/cac-tripplanner-android#197]
Depends on #196. After that issue is done, publish the new version of the app to the Play Store by November 1, 2022.
When publishing, we should also update the "Open Testing" version of the app to the latest version.

Also create issues for upgrading to SDK version 31 by November 1, 2023.

**Comment by ktohalloran** [comment]
Completed via [release 1.4.0](https://github.com/azavea/cac-tripplanner-android/releases/tag/1.4.0). Added new issues for [upgrading](https://github.com/azavea/cac-tripplanner-android/issues/201) and [releasing](https://github.com/azavea/cac-tripplanner-android/issues/202) in 2023.
