### ISSUE TITLE
Upgrade to Android SDK version 33 and triage

### ISSUE THREAD

**Issue by ktohalloran** [azavea/cac-tripplanner-android#208]
We should update to `targetSdkVersion` 33 so that we can get on top of Google's deadlines for releasing to the Play Store. The 2022 update to 30 can be found https://github.com/azavea/cac-tripplanner-android/pull/199.

This task only covers making the change, testing it locally, and making issues for any problems that need to be resolved. It doesn't include fixing problems or publishing to the Play Store. We already know that #213 and #214 will need to be done as part of upgrading.

The deadline for this update in order to release to Google Play Store is August 31, 2023 (we will still be able to have our app in the Google Play store after this date, but will not be able to make any more releases unless we do this first).

**Comment by ddohler** [comment]
I did this and, at least for what we do, there were relatively few changes between SDK 31 and 33. I found 3 new deprecation warnings, which I documented in #217 , but otherwise there were no new deprecation warnings, build errors, or runtime errors that I could find.
