### ISSUE TITLE
Remove Android App from Play Store

### ISSUE THREAD

**Issue by stephwall** [azavea/cac-tripplanner-android#223]
Remove the Android app from the Google Play store on **January 2, 2024**.

**Comment by rajadain** [comment]
As the first step, I'm marking the app as unpublished, which will prevent new users from getting it. This is at the [Google Play Console](https://play.google.com/console/) using the AzaveaDev account.

<img width="1623" alt="image" src="https://github.com/azavea/cac-tripplanner-android/assets/1430060/2950e48e-14a7-4e5c-a9b0-cd317fe00b44">

**Comment by rajadain** [comment]
Will check in an hour if it's still up:

<img width="1623" alt="image" src="https://github.com/azavea/cac-tripplanner-android/assets/1430060/c4c1def1-5ffc-47e4-ba35-de4e2220c57f">

**Comment by rajadain** [comment]
The app is no longer available on Google Play Store https://play.google.com/store/search?q=gophillygo&c=apps&hl=en_US&gl=US:

<img width="1191" alt="image" src="https://github.com/azavea/cac-tripplanner-android/assets/1430060/7818d53a-a2bf-45f8-b229-6d7504eabe83">

I don't think there's a way for us to remove the app from those that already have it on their devices, but this should suffice for now.

We did put up [a message on the main site](https://github.com/azavea/cac-tripplanner/pull/1369) about this. We should decide when to take that down.

**Comment by stephwall** [comment]
Great. I think that's all we need to do for now. I'll let CAC know that it's no longer on the store and see when they'd like us to remove the message from the site.

**Comment by rajadain** [comment]
To further showcase the app's removal, it's URL now 404s: https://play.google.com/store/apps/details?id=org.gophillygo.app

<img width="1623" alt="image" src="https://github.com/azavea/cac-tripplanner-android/assets/1430060/9eb281e0-fc66-4192-b873-ae3b5eac71da">
