### ISSUE TITLE
Write up terms of service

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner-android#60]
Explain what we track and how for the settings screen.

**Comment by jcahail** [comment]
Draft Terms of Service: https://docs.google.com/document/d/1rpir9E4n00s_cAxzoOnhKo37Z99IL1fFt9VeCUy3gfg/edit?usp=sharing

Draft Privacy Policy:
https://docs.google.com/document/d/1sMvL3PRVnV7zYp_f-_tQDEO0TK-lQo8nsdjrK-OPjqQ/edit?usp=sharing
