### ISSUE TITLE
Go to destination detail on second home view carousel click

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner-android#66]
First click on home view carousel should pause the autoplay.

Second click (click after pause on a place's image) should go to the detail view for that place.

**Comment by lederer** [comment]
I don't recall encountering "first tap = pause" in the wild. Is that an Android idiom? If not, I think first tap should go to the detail screen.

**Comment by lederer** [comment]
In the scenario where the carousel page slides away while the user is reading it, they can always swipe it back into place to finish reading.

**Comment by flibbertigibbet** [comment]
It's default behavior currently, unmodified, from a third-party carousel library.

**Comment by lederer** [comment]
Ok cool. Yeah, let's just make first tap go to detail.

**Comment by flibbertigibbet** [comment]
Closed in #108
