### ISSUE TITLE
Rotating device on map view crashes

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner-android#72]
Rotating device to landscape when displaying map causes app to crash.

`
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gophillygo.app/com.gophillygo.app.activities.PlacesMapsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.model.Marker com.google.android.gms.maps.GoogleMap.addMarker(com.google.android.gms.maps.model.MarkerOptions)' on a null object reference
`

**Comment by maurizi** [comment]
It's a little lame, but we could easily fix this by locking the app into portrait only: https://stackoverflow.com/a/4885663

**Comment by flibbertigibbet** [comment]
Locking device orientation only to prevent the activity from crashing is not acceptable; not only does it make for a poor user experience, but it would be masking the underlying issues regarding data loading and state management.

Even if we had a design reason to fix orientation, the app needs to be able to resume consistently from paused/stopped states; switching device orientation is only one way that can happen.
